package:
  name: 'nionutils'
  version: '0.3.21'

source:
  git_rev: 0.3.21
  git_url: https://github.com/nion-software/nionutils.git

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  include_recipe: False

requirements:
  host:
    - python
    - setuptools
  run:
    - python >=3.7

test:
  imports:
    - nion.utils
    - nion.utils.test

about:
  home: https://github.com/nion-software/nionutils
  license: Apache-2.0
  summary: Nion utility classes.
  description: "A utility library of useful Python objects."

extra:
  recipe-maintainers:
    cmeyer
